### PR TITLE
Fix hanging controls by adding missing turbot.error() calls in exception handling. Closes #4

### LINKED ISSUE #4: Controls stuck in "handling" state due to missing `turbot.error()` calls in exception handling
#### Problem

Controls remain stuck in "handling" state when exceptions are thrown during control execution. The `guardrails-lib-fn` library catches exceptions but fails to call `turbot.error()` to transition controls to error state, causing them to never complete.

#### Root Cause

In the migration from callback-based to async/await pattern, the exception handling lost the critical `turbot.error()` calls that were present in the old library. When exceptions occur:

Fatal errors: Correctly call `turbot.error()`
Non-fatal errors: Don't call `turbot.error()` (intentional for retry)

#### Impact

Controls experiencing exceptions remain in "handling" state indefinitely, requiring manual intervention.

### PR DESCRIPTION
**Pull request by Subhajit97**

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ const setAWSEnvVars = ($) => {
   let region = _.get(
     $,
     "item.turbot.custom.aws.regionName",
-    _.get($, "item.turbot.metadata.aws.regionName", _.get($, "item.metadata.aws.regionName")),
+    _.get($, "item.turbot.metadata.aws.regionName", _.get($, "item.metadata.aws.regionName"))
```
Comment (abhiturbot) [inline index.js]:
```suggestion
const region =
  $.item?.turbot?.custom?.aws?.regionName ??
  $.item?.turbot?.metadata?.aws?.regionName ??
  $.item?.metadata?.aws?.regionName;
```

File: index.js [hunk 2]
```diff
@@ -560,14 +559,15 @@ const finalize = async (event, context, init, err, result) => {
           console.error("Error in send function", { error: _err });
           reject(_err);
         } else {
+          console.info("Send operation completed successfully");
```
Comment (abhiturbot) [inline index.js]:
```suggestion
```

File: index.js [hunk 3]
```diff
@@ -597,41 +597,51 @@ function gfn(asyncHandler) {
...
+            `Unexpected non-fatal error while executing Lambda function. Lambda will be retried based on AWS Lambda retry policy`,
+            {
+              error: err,
+              mode: _mode,
+            }
+          );
+          finalError = err;
+        } else {
+          console.error("Caught exception while executing the handler", { error: err, event, context });
+          finalError = err;
```
[the remark this answers is not in the document]
Comment (Subhajit97) [reply index.js:632]: @abhiturbot, should we handle this? I can see we've not raised any commands if there is an unknown exception.

**Review by abhiturbot — APPROVED** [review]
